# Alexander Tebiev - https://github.com/beeyev

services:
  phpmyadmin:
    image: ghcr.io/beeyev/phpmyadmin-docker-lightweight:test
    container_name: 'phpmyadmin'
    restart: unless-stopped
    tty: true
    environment:
      - 'TZ=CET'
      - 'PMA_HOST=mysql'
      - 'PMA_USER=root'
      - 'PMA_PASSWORD=TestRootPassword'
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - network1

  mysql:
    image: bitnami/mysql:8.0
    container_name: 'mysql'
    restart: unless-stopped
    tty: true
    environment:
      - 'TZ=CET'
      - 'MYSQL_ROOT_PASSWORD=TestRootPassword'
    networks:
      - network1

networks:
  network1:
    driver: bridge
